version: "3.7"

services:
  postgresql:
    image: postgres:11.5
    environment:
      POSTGRES_DB: hashbash
      POSTGRES_PASSWORD: postgres
    ports:
      - published: 5432
        target: 5432

  migrate:
    image: jnorwood/hashbash-migrate:current
    build:
      context: ..
      dockerfile: docker/Dockerfile-migrate
    depends_on:
      - postgresql
    entrypoint:
      - bash
      - -c
      - >
        /opt/scripts/wait-for-it postgresql:5432 -t 300
        && /migrate \
          -database postgresql://postgres:postgres@postgresql/hashbash?sslmode=disable \
          -path . \
          up
    volumes:
      - type: bind
        source: ../migrate-versions
        target: /opt/migrate
      - type: bind
        source: ../scripts
        target: /opt/scripts
        read_only: true

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - published: 5672
        target: 5672
      - published: 15672
        target: 15672
      - published: 55672
        target: 55672

  nginx:
    image: jnorwood/hashbash-nginx:23.0724.0
    volumes:
      - type: volume
        source: hashbash-sockets
        target: /run/hashbash
      - type: volume
        source: hashbash-nginx-runtime
        target: /run/hashbash-nginx

  socat:
    image: jnorwood/hashbash-socat:current
    build:
      context: docker
      dockerfile: Dockerfile-socat
    ports:
      - published: 80
        target: 23080
    volumes:
      - type: volume
        source: hashbash-nginx-runtime
        target: /run/hashbash-nginx

volumes:
  hashbash-sockets:
  hashbash-nginx-runtime:
