version: "3.7"

services:
  postgresql:
    image: postgres:11.5
    environment:
      POSTGRES_DB: hashbash
      POSTGRES_PASSWORD: postgres
    ports:
      - published: 5432
        target: 5432

  migrate:
    image: migrate/migrate
    depends_on:
      - postgresql
    entrypoint:
      - sh
      - -c
      - >
          echo "sleeping 3 seconds to allow database to start" &&
          sleep 3 &&
          /migrate \
            -database postgresql://postgres:postgres@postgresql/hashbash?sslmode=disable \
            -source file://versions \
            up
    volumes:
      - type: bind
        source: ../migrate-versions
        target: /opt/migrate/versions
    working_dir: /opt/migrate

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - published: 5672
        target: 5672
      - published: 15672
        target: 15672
      - published: 55672
        target: 55672

  nginx:
    image: jnorwood/hashbash-nginx:release-20190425-1647
    extra_hosts:
      - hashbash-webapp:${HASHBASH_HOST_IP_ADDRESS}
    ports:
      - published: 80
        target: 80

  hashbash-engine:
    image: jnorwood/hashbash-consumers-go:current
    build:
      context: ..
      dockerfile: docker/Dockerfile-engine
    depends_on:
      - postgresql
      - rabbitmq
    environment:
      HASHBASH_DATABASE_ENGINE: postgresql
      HASHBASH_DATABASE_HOST: postgresql
      HASHBASH_DATABASE_SSL_MODE: disable
      HASHBASH_DATABASE_USERNAME: postgres
      HASHBASH_DATABASE_PASSWORD: postgres
      HASHBASH_RABBITMQ_HOST: rabbitmq
      HASHBASH_INITIAL_DELAY: 15s
      HASHBASH_MANAGEMENT_PORT: 8082
    ports:
      - published: 8082
        target: 8082

  hashbash-webapp:
    image: jnorwood/hashbash-webapp-go:current
    build:
      context: ..
      dockerfile: docker/Dockerfile-webapp
    depends_on:
      - postgresql
      - rabbitmq
    environment:
      HASHBASH_DATABASE_ENGINE: postgresql
      HASHBASH_DATABASE_HOST: postgresql
      HASHBASH_DATABASE_SSL_MODE: disable
      HASHBASH_DATABASE_USERNAME: postgres
      HASHBASH_DATABASE_PASSWORD: postgres
      HASHBASH_RABBITMQ_HOST: rabbitmq
      HASHBASH_INITIAL_DELAY: 15s
    ports:
      - published: 8080
        target: 8080
      - published: 8081
        target: 8081
