# Download dependencies and build the binary
FROM golang:1.20-bookworm@sha256:832f2f74baa3e2b00ace688cb2fa934dffeade39f5b4c0cc8b1cff8d3fb084a0 AS build
LABEL maintainer=norwood.john.m@gmail.com

WORKDIR /opt/hashbash
COPY go.mod go.sum ./
RUN go mod download

COPY . ./
WORKDIR /opt/hashbash/cmd/hashbash-engine
RUN go build


# Copy built binary into the final image
FROM debian:bookworm-20230703@sha256:60774985572749dc3c39147d43089d53e7ce17b844eebcf619d84467160217ab
COPY --from=build /opt/hashbash/cmd/hashbash-engine/hashbash-engine /
EXPOSE 8081
ENTRYPOINT ["/hashbash-engine"]
