version: "3"

volumes:
  frontend-public-volume:

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
      - 55672:55672

  nginx:
    image: jnorwood/hashbash-nginx:release-20190425-1647
    depends_on:
      - hashbash-webapp
    ports:
      - 80:80

  hashbash-consumers:
    image: jnorwood/hashbash-consumers-go:current
    depends_on:
      - mysql
      - rabbitmq
    environment:
      HASHBASH_DATABASE_HOST: mysql
      HASHBASH_RABBITMQ_HOST: rabbitmq
      HASHBASH_INITIAL_DELAY: 10s
      HASHBASH_LOG_LEVEL: debug
      HASHBASH_PROMETHEUS_PORT: 8082
    ports:
      - 8082:8082

  hashbash-webapp:
    image: jnorwood/hashbash-webapp-go:current
    depends_on:
      - mysql
      - rabbitmq
    environment:
      HASHBASH_DATABASE_HOST: mysql
      HASHBASH_RABBITMQ_HOST: rabbitmq
      HASHBASH_INITIAL_DELAY: 10s
      HASHBASH_LOG_LEVEL: debug
    ports:
      - 8081:8081
