version: "3.7"

services:
  postgresql:
    image: postgres:14-bookworm@sha256:3be9a3ad9e8308654b9d26ed2dd0be1767cff86c2d8d31d6125f188735e47d7f
    environment:
      POSTGRES_DB: hashbash
      POSTGRES_PASSWORD: postgres

  rabbitmq:
    image: rabbitmq:3.9-management@sha256:74c6f00ed725ca77d8c0d416e01e99cfbaba17aa77bc2d2846d9c0066ab5be61

  nginx:
    image: jnorwood/hashbash-nginx:2023.8.1
    volumes:
      - type: volume
        source: hashbash-sockets
        target: /run/hashbash
      - type: volume
        source: hashbash-nginx-runtime
        target: /run/hashbash-nginx
      - type: volume
        source: hashbash-nginx-logs
        target: /run/systemd/journal

  migrate:
    image: jnorwood/hashbash-migrate
    build:
      context: ..
      dockerfile: docker/Dockerfile-migrate
    depends_on:
      - postgresql
    entrypoint:
      - bash
      - -c
      - >
        /opt/scripts/wait-for-it postgresql:5432 -t 300
        && /migrate \
          -database postgresql://postgres:postgres@postgresql/hashbash?sslmode=disable \
          -path . \
          up
    volumes:
      - type: bind
        source: ../migrate-versions
        target: /opt/migrate
      - type: bind
        source: ../scripts
        target: /opt/scripts
        read_only: true

  journald:
    image: jnorwood/hashbash-journald
    build:
      context: docker
      dockerfile: Dockerfile-journald
    volumes:
      - type: volume
        source: hashbash-nginx-logs
        target: /run/systemd/journal

  socat:
    image: jnorwood/hashbash-socat
    build:
      context: docker
      dockerfile: Dockerfile-socat
    ports:
      - published: 23280
        target: 23080
    volumes:
      - type: volume
        source: hashbash-nginx-runtime
        target: /run/hashbash-nginx

volumes:
  hashbash-sockets:
  hashbash-nginx-logs:
  hashbash-nginx-runtime:
