# Download dependencies and build the binary
FROM golang:1.13-alpine AS build
LABEL maintainer=norwood.john.m@gmail.com

COPY go.mod go.sum /opt/hashbash/
WORKDIR /opt/hashbash
RUN apk add --no-cache git \
    && go mod download

COPY . /opt/hashbash/
WORKDIR /opt/hashbash/cmd/hashbash-engine
RUN go build -ldflags "-X main.Version=$(cat /opt/hashbash/version.txt)"


# Copy built binary into the final image
FROM alpine:3.9
COPY --from=build /opt/hashbash/cmd/hashbash-engine/hashbash-engine /
EXPOSE 8081
ENTRYPOINT ["/hashbash-engine"]
